### ISSUE TITLE
MoveTo - Line 148

### ISSUE THREAD

**Issue by toetag-yim** [Dragonfoot/mountain#1]
"go hub" - go command not handling exits with multiple words,  ie:  Transit Hub exit.  unhandled exception

"go con" - go command not handling exits that don't exist. ie: when in control room, if user tries to "go con", unhandled exception.

**Comment by Dragonfoot** [comment]
Thanks, I'd put an exception in there to catch nullreference, intending to respond to it once something else got done, nice catch.
