### ISSUE TITLE
enums built from XML instead of hard coded

### ISSUE THREAD

**Issue by toetag-yim** [Dragonfoot/mountain#2]
pull enums out of globals.cs and have it pull them from XML files.   Possibly a "reload enums" command to reload enums on the fly instead of stopping and starting server.

**Comment by Dragonfoot** [comment]
Enum 'types' themselves would still need to be hard coded, if not their values. Changing an enum value outside the engine would very likely unbind the coding logic that already relies on them. Adding a value to a type would likely be the only way we could go seeing as the code's not been written yet. I also have a worry that keeping the values outside the code leaves room for editing mistakes, which could have us looking at unexpected exceptions or crashes.

**Comment by toetag-yim** [comment]
Isn't that a good programmers job,  testing and preventing crashes?  Ie: keeping users from doing stupid things?

**Comment by Dragonfoot** [comment]
I understand the idea you have for it I think, expansion for others later down the road. 

Think of an Enum as a constant, fixed in stone once code has started depending on it, such as in switches or bitwise manipulations. Adding a constant to an already defined Enum means code has been planned for its use, or why add.

Plugin's may be the better approach. Having a **generic** enum _simulator_ of some sort might be possible when dealing with a plugin. Placing the simulated enum values in file might become doable, as it may be feasible within some sort of scripting module, where an interpreter could decide how to handle it based on the script it accompanies. 

I'm still learning as we go here, and new things yet to know could come up to change this. I'll leave this open for you to decide how you might want to go with it.

**Comment by toetag-yim** [comment]
Perhaps this is more of a feature suggestion than an issue.

In my head, we'll use "a new spell" as an example.

modify spells.xml with the new spell information.
Then a command for the admin to run,  "reload spells
The first thing the command would do is validate the xml structure
    if structure valid,  clear memory of spells and reload from xml file
    if structure invalid, pass error  "Reload failed, spells.xml format is in error".

**Comment by Dragonfoot** [comment]
I like the idea of feature suggestions in here, keep them coming.

On your spell addition idea you're using here, I'm assuming this is being done after the program is out of our hands. 

I'd want to have a generic spell method established. It would be passed a data packet with class of spell, the caster, his target(s), effects he and the room occupants are exposed to, restrictions, etc. Loading in a new spell from file would then have some of those parameters as part of its data. 

We'd need a help packet to go with it for the players as well. Your earlier idea of saving data to file could be used here, like when building and adding a room to an area, it's then saved as part of the area; spells and the like could be handled in a similar way. A core set of hard coded spells then, to start the game off with, and game builder's input files, perhaps from templates, to augment them with.

We wouldn't require a reload here as we're using generic dictionaries for commands like this already. Adding a new spell to the current ones; a simple enough step. 

I may start calling you Validator in the game. :smile:

**Comment by toetag-yim** [comment]
real quick,   a "spell" object would have to have a common structure.   A user couldn't add a new spell to "spell.xml"  and create a new spell property through it necessarily.  any new property/structure of the spell object would have to be coded.  

for example say the structure is

`<name>`fireball`</name>`
`<class>`mage`</class>`
`<race>`human`</race>`
`<elemet>`fire`</element>`
`<level>`2`</level>`

a player couldn't add a new spell to spell.xml with structure as such:

`<name>`light`</name>`
`<class>`cleric`</class>`
`<race>`elf`</race>`
`<elemet>`fire`</element>`
`<level>`2`</level>`
`<duration>`2`<duration>`

Comes down to when we are building the object structure, to include as much as possible from the start.  Heck, come to think of it we can have commands in the game to act as a wizard "add new `<object>`"  that reads the structure of the object,  prompts the admin to input the right properties, then save to the xml file

help files and documentation will be a must.   a builders manual, admin manual,  in game help files.

**Comment by Dragonfoot** [comment]
I'm closing this conversation as I think we covered the basics on future expansion ideas.
